datasource:
  enabled: true

spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: H2
    hibernate:
      ddl-auto: none

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE